"""Builds docs/reference_codes.md and docs/reference_order_processing.md.

Unlike build_data_dictionary.py, this reads src/rcl_datagen/reference_codes.py
directly rather than generated output — it has no dependency on
scripts/generate.py having run, since it documents the fixed code domains,
not the generated data. Run it any time reference_codes.py changes.

These two files are the "reference documents" the question bank's Data brief
calls for (section 7): short synthetic docs on codes and order processes,
so the chatbot's retrieval path has something concrete to route "what does
code X mean" and "how is a rejection recorded" questions to, and can name
its source document when it answers one.
"""
from __future__ import annotations

import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR / "src"))

from rcl_datagen import reference_codes as rc  # noqa: E402

_HEADER = (
    "Auto-generated by `scripts/build_reference_docs.py`. Do not hand-edit — "
    "update `src/rcl_datagen/reference_codes.py` instead and rerun."
)


def _code_table(pairs) -> list[str]:
    lines = ["| Code | Meaning |", "|---|---|"]
    for code, desc in pairs:
        if code is None:
            continue
        lines.append(f"| {code} | {desc} |")
    return lines


def _build_reference_codes_md() -> str:
    lines = [
        "# RCL PoC - Reference Codes",
        "",
        _HEADER,
        "",
        "Every code domain the generator draws from, in one place — so a "
        "retrieval answer to \"what does code X mean\" always matches what "
        "the generated data actually contains.",
        "",
        "## Delivery block codes",
        "",
        *_code_table(rc.DELIVERY_BLOCK_CODES),
        "",
        "## Billing block codes",
        "",
        *_code_table(rc.BILLING_BLOCK_CODES),
        "",
        "## Credit block codes",
        "",
        *_code_table(rc.CREDIT_BLOCK_CODES),
        "",
        "## Order rejection reasons",
        "",
        *_code_table(rc.REJECTION_CODES),
        "",
        "## Order cancellation reasons",
        "",
        *_code_table(rc.CANCELLATION_REASON_CODES),
        "",
        "## Order cut reasons",
        "",
        *_code_table(rc.CUT_REASON_CODES),
        "",
        "## Order types",
        "",
        *_code_table(rc.ORDER_TYPE_CODES),
        "",
        "## Allocation reason codes (KC)",
        "",
        *_code_table(rc.KC_CODES),
        "",
    ]
    return "\n".join(lines)


def _build_reference_order_processing_md() -> str:
    return "\n".join([
        "# RCL PoC - Order Processing Reference",
        "",
        _HEADER,
        "",
        "## How a rejection gets recorded",
        "",
        "When an order line can't be filled as requested, it's flagged with a "
        "rejection reason rather than silently reduced. Open orders (the "
        "`shipments` table) carry a single `Rj`/`Rejection_Description` pair. "
        "Historical orders (the `historical` table) carry both a primary and "
        "an optional secondary rejection reason (`RJCTN_RSN_PRIM_CD`/`_DESC`, "
        "`RJCTN_RSN_SECO_CD`/`_DESC`) — see `docs/reference_codes.md` for the "
        "full code list.",
        "",
        "## How a cut gets recorded",
        "",
        "A cut is the gap between what was ordered and what was actually "
        "delivered on a historical order line (`historical.CUT_QTY == "
        "historical.ORDR_QTY - historical.DELV_QTY`). Every cut line carries a "
        "primary cut reason (`CUT_RSN_PRIM_CD`/`_DESC`); a portion also carry "
        "a secondary one. `\"Allocation\"` is one such reason, used when the "
        "material's parent product was flagged on-allocation "
        "(`allocation.ALLOC_STATUS == 'On Allocation'`) during the order's "
        "planned goods-issue week — that's what makes a cut traceable back "
        "to a real allocation constraint rather than an unexplained shortfall.",
        "",
        "## How a block gets recorded",
        "",
        "Open-order lines (`shipments`) and historical delivery headers "
        "(`historical.DELV_HDR_BLK_CD`) can each carry a delivery block. "
        "`shipments` additionally distinguishes delivery, billing, and credit "
        "blocks as three separate fields, since each stops the order for a "
        "different reason (fulfillment hold, invoicing hold, and payment-risk "
        "hold respectively).",
        "",
        "## Order types excluded from fill-rate and on-time metrics",
        "",
        "`historical.ORDR_TYPE_CD`/`_DESC` marks each line as Standard, "
        "Return, Free Goods, Sample, or Intercompany. Fill-rate, cut, "
        "rejection, and on-time metrics are meant to be computed over "
        "Standard order lines only — returns, free goods, samples, and "
        "intercompany transfers aren't customer-facing sales and would "
        "distort those rates if included. `historical.CANCELLED_FL == "
        "'YES'` lines should also be excluded from fill-rate math (a "
        "cancellation isn't a shortfall the supply chain caused), though the "
        "raw `CUT_QTY` field is still populated for them (see "
        "`docs/data_dictionary.md`).",
        "",
        "## Fill rate — which one?",
        "",
        "This dataset supports three distinct fill-rate definitions, and "
        "they should not be mixed:",
        "",
        "- **Historical (unit) fill rate**: `SUM(historical.DELV_QTY) / "
        "SUM(historical.ORDR_QTY)`, over Standard, non-cancelled lines. A "
        "backward-looking, realized rate.",
        "- **Forward (open-order) fill rate**: `SUM(shipments.Confirmed_Qty) "
        "/ SUM(shipments.Order_Quantity)`. What SAP currently expects to "
        "ship against the open book — not yet realized.",
        "- **Dollar fill rate**: either of the above computed on "
        "`*_VAL`/`GTS_*` value columns instead of quantity columns.",
        "",
        "See `docs/data_dictionary.md` for exact column definitions.",
        "",
    ])


def main() -> None:
    docs_dir = BASE_DIR / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)

    codes_path = docs_dir / "reference_codes.md"
    codes_path.write_text(_build_reference_codes_md(), encoding="utf-8")
    print(f"Wrote {codes_path}")

    process_path = docs_dir / "reference_order_processing.md"
    process_path.write_text(_build_reference_order_processing_md(), encoding="utf-8")
    print(f"Wrote {process_path}")


if __name__ == "__main__":
    main()
