"""Builds docs/data_dictionary.md from the most recently generated tables.

Run after scripts/generate.py. Reads output/parquet/*.parquet rather than
regenerating anything, so the dictionary always reflects exactly what was
last generated — this is the stand-in for the client's "General Knowledge /
Data Dictionary" unstructured source.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR / "src"))

from rcl_datagen.metadata import TABLE_DESCRIPTIONS, build_data_dictionary  # noqa: E402


def main() -> None:
    parquet_dir = BASE_DIR / "output" / "parquet"
    files = sorted(parquet_dir.glob("*.parquet"))
    if not files:
        raise SystemExit(f"No generated tables found in {parquet_dir} - run scripts/generate.py first.")

    tables = {f.stem: pd.read_parquet(f) for f in files}
    dictionary = build_data_dictionary(tables)

    lines = [
        "# RCL PoC - Data Dictionary",
        "",
        "Auto-generated by `scripts/build_data_dictionary.py`. Do not hand-edit — "
        "update `src/rcl_datagen/metadata.py` instead and rerun.",
        "",
    ]

    for table in tables:
        lines.append(f"## `{table}`")
        lines.append("")
        lines.append(TABLE_DESCRIPTIONS.get(table, ""))
        lines.append("")
        lines.append("| Column | Type | Example | Description |")
        lines.append("|---|---|---|---|")
        for _, row in dictionary[dictionary["table"] == table].iterrows():
            example = "" if row["example_value"] is None else str(row["example_value"])
            example = example.replace("|", "\\|")[:60]
            description = str(row["description"]).replace("|", "\\|")
            lines.append(f"| {row['column']} | {row['dtype']} | {example} | {description} |")
        lines.append("")

    out_path = BASE_DIR / "docs" / "data_dictionary.md"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path} ({len(dictionary)} columns across {len(tables)} tables)")


if __name__ == "__main__":
    main()
