"""Runs every question in queries/order_intelligence.py against the generated
DuckDB and writes docs/sample_qa_output.md.

This is both the "Q&A - Order Intelligence" seed content and a smoke test —
if a query errors or returns zero rows, something upstream likely broke. Run
after scripts/generate.py.
"""
from __future__ import annotations

import sys
from pathlib import Path

import duckdb

BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR / "src"))
sys.path.insert(0, str(BASE_DIR))

from queries.order_intelligence import QUESTIONS  # noqa: E402


def main() -> None:
    db_path = BASE_DIR / "output" / "rcl_poc.duckdb"
    if not db_path.exists():
        raise SystemExit(f"{db_path} not found - run scripts/generate.py first.")

    con = duckdb.connect(str(db_path), read_only=True)
    lines = [
        "# RCL PoC - Sample Order-Intelligence Q&A",
        "",
        "Auto-generated by `scripts/run_sample_questions.py` against the current "
        "generated dataset. Add new questions in `queries/order_intelligence.py` "
        "and rerun — don't hand-edit this file.",
        "",
    ]

    had_error = False
    for q in QUESTIONS:
        lines.append(f"## {q.question}")
        lines.append("")
        lines.append("```sql")
        lines.append(q.sql.strip())
        lines.append("```")
        lines.append("")
        try:
            result = con.execute(q.sql).fetch_df()
        except Exception as exc:  # noqa: BLE001 - report every failure, then keep going
            lines.append(f"**ERROR:** {exc}")
            lines.append("")
            had_error = True
            continue

        if result.empty:
            lines.append("_(no rows returned)_")
        else:
            preview = result.head(10)
            lines.append("| " + " | ".join(preview.columns) + " |")
            lines.append("|" + "---|" * len(preview.columns))
            for _, row in preview.iterrows():
                lines.append("| " + " | ".join(str(v) for v in row.tolist()) + " |")
        lines.append("")

    con.close()
    out_path = BASE_DIR / "docs" / "sample_qa_output.md"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path} ({len(QUESTIONS)} questions)")
    if had_error:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
